config/routes.rb
Rails.application.routes.draw do
  get 'photopage/about'
  get 'photopage/gallery'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "photopage#gallery"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photopage_controller.rb
class PhotopageController < ApplicationController
  def about
  end

  def gallery
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photopage_helper.rb
module PhotopageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accelerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Ioonos fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
 
   
  </head>

  <body class="is-preload-0 is-preload-1 is-preload-2">
    <!-- Main -->
		<div id="main">

            

   <%= yield %>


    <!-- Footer -->
					<footer id="footer">
						<ul class="copyright">
							<li>&copy; Untitled.</li><li>Design: <a href="https://github.com/JuanFranciscoAR/accelerator ">Juan Francisco armijo</a>.</li>
						</ul>
					</footer>
    </div>

        <!-- Bootstraps -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    		<!-- Scripts -->
        <%= javascript_include_tag 'jquery.min.js' %>
        <%= javascript_include_tag 'browser.min.js' %>
        <%= javascript_include_tag 'breakpoints.min.js' %>
        <%= javascript_include_tag 'main.js' %>



  </body>
</html>

app/views/photopage/about.html.erb
           
         
            <!-- Header -->
                    <header id="header">
						<h1>Conóceme</h1>
                        <nav class="navbar bg-body-tertiary">
                            <form class="container-fluid justify-content-start">

<%= link_to "Mis fotografías", root_path, class: "btn btn-primary", id: "btnRedirectReload" %>

<script>
  document.getElementById("btnRedirectReload").addEventListener("click", function() {
    // Redirige a la nueva página
    window.location.href = "<%= root_path %>";

    // Recarga la página después de 1 segundo (1000 milisegundos)
    setTimeout(function() {
      location.reload();
    }, 1000);
  });
</script>


                        </form>
                        </nav>
 
						<p>Tomadas en de mis viajes <a href="http://html5up.net/lens"> - Link Lens</a></p>
						<ul class="icons">
							<li><a href="#" class="icon brands fab fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
							<li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
						</ul>
					</header>

 <!-- Thumbnail -->
					<section id="thumbnails">
						<article>
                <%= link_to image_path('fulls/01.jpg'), class: "thumbnail", data: { position: "left center" } do %>
                    <%= image_tag '', alt: "" %>
                    <% end %>

							<h2>Diam tempus accumsan</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/02.jpg'), class: "thumbnail" do %>
                    <%= image_tag '', alt: "" %>
                    <% end %>
						
							<h2>Vivamus convallis libero</h2>
							<p>Sed velit lacus, laoreet at venenatis convallis in lorem tincidunt.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/03.jpg'), class: "thumbnail" do %>
                                    <%= image_tag '', alt: "" %>
                                    <% end %>

							<h2>Nec accumsan enim felis</h2>
							<p>Maecenas eleifend tellus ut turpis eleifend, vitae pretium faucibus.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/04.jpg'), class: "thumbnail" do %>
                                    <%= image_tag '', alt: "" %>
                                    <% end %>
							<h2>Donec maximus nisi eget</h2>
							<p>Tristique in nulla vel congue. Sed sociis natoque parturient nascetur.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/05.jpg'), class: "thumbnail" do %>
                                    <%= image_tag '', alt: "" %>
                                    <% end %>
							<h2>Nullam vitae nunc vulputate</h2>
							<p>In pellentesque cursus velit id posuere. Donec vehicula nulla.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/06.jpg'), class: "thumbnail" do %>
                                    <%= image_tag '', alt: "" %>
                                    <% end %>
							<h2>Phasellus magna faucibus</h2>
							<p>Nulla dignissim libero maximus tellus varius dictum ut posuere magna.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/07.jpg'), class: "thumbnail" do %>
                                    <%= image_tag '', alt: "" %>
                                    <% end %>
							<h2>Proin quis mauris</h2>
							<p>Etiam ultricies, lorem quis efficitur porttitor, facilisis ante orci urna.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/08.jpg'), class: "thumbnail" do %>
                                    <%= image_tag '', alt: "" %>
                                    <% end %>
							<h2>Gravida quis varius enim</h2>
							<p>Nunc egestas congue lorem. Nullam dictum placerat ex sapien tortor mattis.</p>
						</article>
				
						</article>
					</section>

                    

                    <section id="thumbnails">
                    		<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porta lorem et iaculis ornare.
                                Vestibulum vitae ex nunc. Suspendisse bibendum pharetra neque eu hendrerit. Donec ut lectus id puru metus.
                                Ut nunc est, maximus nec placerat non, vehicula non augue. Duis neque purus, faucibus sed ante.
                            </p>

                  		    <p> 
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porta lorem et iaculis ornare.
                                Vestibulum vitae ex nused ante Ut nunc est, maximus nec placerat non, vehicula non augue. Duis neque purus, faucibus sed ante.
                            </p>
                    </section>

app/views/photopage/gallery.html.erb
          
          
          <!-- Header -->

          
		<header id="header">
			   <h1>Mis fotografías</h1>
            <nav class="navbar bg-body-tertiary">
                <form class="container-fluid justify-content-start">
<%= link_to "Conóceme", photopage_about_path, class: "btn btn-primary", id: "btnRedirectReload" %>

<script>
  document.getElementById("btnRedirectReload").addEventListener("click", function() {
    // Redirige a la nueva página
    window.location.href = "<%= photopage_about_path %>";

    // Recarga la página después de 1 segundo (1000 milisegundos)
    setTimeout(function() {
      location.reload();
    }, 1000);
  });
</script>

              </form>
            </nav>
 
						<p>Tomadas en de mis viajes <a href="http://html5up.net/lens"> - Link Lens</a></p>
						<ul class="icons">
							<li><a href="#" class="icon brands fab fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
							<li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
						</ul>
		</header>
                       
          
          <!-- Thumbnail -->
					<section id="thumbnails">
						<article>
                <%= link_to image_path('fulls/01.jpg'), class: "thumbnail", data: { position: "left center" } do %>
                    <%= image_tag 'thumbs/01.jpg', alt: "" %>
                    <% end %>

							<h2>Diam tempus accumsan</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/02.jpg'), class: "thumbnail" do %>
                    <%= image_tag 'thumbs/02.jpg', alt: "" %>
                    <% end %>
						
							<h2>Vivamus convallis libero</h2>
							<p>Sed velit lacus, laoreet at venenatis convallis in lorem tincidunt.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/03.jpg'), class: "thumbnail" do %>
                                    <%= image_tag 'thumbs/03.jpg', alt: "" %>
                                    <% end %>

							<h2>Nec accumsan enim felis</h2>
							<p>Maecenas eleifend tellus ut turpis eleifend, vitae pretium faucibus.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/04.jpg'), class: "thumbnail" do %>
                                    <%= image_tag 'thumbs/04.jpg', alt: "" %>
                                    <% end %>
							<h2>Donec maximus nisi eget</h2>
							<p>Tristique in nulla vel congue. Sed sociis natoque parturient nascetur.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/05.jpg'), class: "thumbnail" do %>
                                    <%= image_tag 'thumbs/05.jpg', alt: "" %>
                                    <% end %>
							<h2>Nullam vitae nunc vulputate</h2>
							<p>In pellentesque cursus velit id posuere. Donec vehicula nulla.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/06.jpg'), class: "thumbnail" do %>
                                    <%= image_tag 'thumbs/06.jpg', alt: "" %>
                                    <% end %>
							<h2>Phasellus magna faucibus</h2>
							<p>Nulla dignissim libero maximus tellus varius dictum ut posuere magna.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/07.jpg'), class: "thumbnail" do %>
                                    <%= image_tag 'thumbs/07.jpg', alt: "" %>
                                    <% end %>
							<h2>Proin quis mauris</h2>
							<p>Etiam ultricies, lorem quis efficitur porttitor, facilisis ante orci urna.</p>
						</article>
						<article>
                <%= link_to image_path('fulls/08.jpg'), class: "thumbnail" do %>
                                    <%= image_tag 'thumbs/08.jpg', alt: "" %>
                                    <% end %>
							<h2>Gravida quis varius enim</h2>
							<p>Nunc egestas congue lorem. Nullam dictum placerat ex sapien tortor mattis.</p>
						</article>
				
						</article>
					</section>

                    